### ISSUE TITLE
Make generator json for solidity

### ISSUE THREAD

**Issue by user090909** [everx-labs/TVM-Solidity-Compiler#103]
Hello. I have a problem with generating json objects onchain. For example with tip4_2 we can change json on chain but for now its a bit hard 
`_json = '{"type": "Basic Nft", "name": "Opened nft lootbox","preview": {"source":"' + format("{}",_img.link) +'","mimetype":"' + format("{}", _img.mimetype) + '"}}';` 
we need to do such constructions where  we can easily put a mistake. Probably, json generators like in python could help with this problems?

**Comment by user090909** [comment]
https://gist.github.com/user090909/51bf389ae1914bee0e59b342216d5a4e

**Comment by cryshado** [comment]
@user090909 Thanks for the issue. Currently we don't plan to build JSON serialization into the language's capabilities yet, but you can still easily implement such a serializer by following the information at www.json.org
