### ISSUE TITLE
cmake --build . -- -j8

### ISSUE THREAD

**Issue by Lexzandr** [everx-labs/TVM-Solidity-Compiler#105]
cmake --build . -- -j8
[ 37%] Built target jsoncpp-project
[ 37%] Built target solidity_BuildInfo.h
Consolidate compiler generated dependencies of target solutil
[ 37%] Built target solutil
Consolidate compiler generated dependencies of target langutil
[ 37%] Built target langutil
Consolidate compiler generated dependencies of target solidity
[ 37%] Building CXX object libsolidity/CMakeFiles/solidity.dir/codegen/TVMContractCompiler.cpp.o
/Users/lexzandr/TON-Solidity-Compiler/compiler/libsolidity/codegen/TVMContractCompiler.cpp:192:12: error: implicit instantiation of undefined template 'std::basic_ofstream<char>'
                ofstream ofile;
                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/iosfwd:151:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_ofstream;
                               ^
/Users/lexzandr/TON-Solidity-Compiler/compiler/libsolidity/codegen/TVMContractCompiler.cpp:211:14: error: implicit instantiation of undefined template 'std::basic_ofstream<char>'
    ofstream ofile;
             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/iosfwd:151:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_ofstream;
                               ^
2 errors generated.
make[2]: *** [libsolidity/CMakeFiles/solidity.dir/codegen/TVMContractCompiler.cpp.o] Error 1
make[1]: *** [libsolidity/CMakeFiles/solidity.dir/all] Error 2
make: *** [all] Error 2

**Comment by ilyar** [comment]
@Lexzandr try

```shell
git@github.com:EverscaleGuild/ever-solidity.git
cd ever-solidity
make release
./release/sold -h
```
or get binary https://github.com/EverscaleGuild/ever-solidity/releases

**Comment by IgorKoval** [comment]
Thank you. We had such problem. You can add `#include <fstream>` to file `TVMContractCompiler.cpp` to build it.
