### ISSUE TITLE
Missed elements in AST tree

### ISSUE THREAD

**Issue by pizza-777** [everx-labs/TVM-Solidity-Compiler#121]
The responsible function has specific returns with {parameters} like this:
``` 
return { value: 0, bounce: false, flag: MsgFlag.REMAINING_GAS } (left_wallet, right_wallet, lp_wallet);
```
( source [DexPair.sol](https://github.com/broxus/flatqube-contracts/blob/master/contracts/DexPair.sol)  )

I generate an AST tree with the command
```
everdev sol ast --format compact-json DexPair.sol
```
But the AST tree doesn't have these parameters.

**Comment by IgorKoval** [comment]
Thank you, fixed in 0.68.0 version
