### ISSUE TITLE
Bug: invalid decode inside afterSignatureCheck function passes compilation

### ISSUE THREAD

**Issue by FairyFromAlfeya** [everx-labs/TVM-Solidity-Compiler#123]
### Example:

https://github.com/tonlabs/evernode-se/blob/master/contracts/giver_v3/GiverV3.sol#L58

### Description:

`(, uint64 expireAt) = body.decode(uint64, uint32);`
Mismatch between left and right types

**Comment by IgorKoval** [comment]
Fixed
