### ISSUE TITLE
Segmentation fault: 11 for numbers more than 2**256 - 1 inside math.muldiv()

### ISSUE THREAD

**Issue by FairyFromAlfeya** [everx-labs/TVM-Solidity-Compiler#127]
Explanation:

code `math.muldiv(2**256, 123, 2);` throws runtime exception of solc

`[ERROR]  /bin/sh: line 1: 54600 Segmentation fault: 11  /Users/fairyfromalfeya/Library/Caches/locklift-nodejs/compiler/0_61_2/solc_0_61_2_darwin`

Correct behavior:

The user will receive a compilation error with message like: first argument 2**256 is more than max possible value for uint256

**Comment by IgorKoval** [comment]
Thank you for reporting, we will solve it!
