### ISSUE TITLE
pragma version error

### ISSUE THREAD

**Issue by pizza-777** [everx-labs/TVM-Solidity-Compiler#132]
![IMG_20230504_101246_559.jpg](https://user-images.githubusercontent.com/26024499/236135781-cb58c444-49fe-4ba2-90f4-ef111a553ff2.jpg)
Please consider changing the pragma version "error" to a "warning".

Because if I comment out this line, the contract is compiled successfully. So it's more warning than error.

**Comment by IgorKoval** [comment]
Yes, it is. But according to original docs:
https://docs.soliditylang.org/en/latest/layout-of-source-files.html#version-pragma
`It just instructs the compiler to check whether its version matches the one required by the pragma. If it does not match, the compiler issues an error.`
