### ISSUE TITLE
Potential Optimizations in TON Solidity Compiler

### ISSUE THREAD

**Issue by pyAndr3w** [everx-labs/TVM-Solidity-Compiler#135]
This issue aims to identify and address potential optimizations in the TON Solidity Compiler, specifically focusing on areas in the generated assembly code that can be optimized.

The objective of this issue is to improve the performance and efficiency of the TON Solidity Compiler by identifying specific areas within the generated assembly code that can be optimized. By optimizing the code, we can enhance the overall execution speed and reduce the gas consumption of smart contracts deployed on TVM-based blockchains.

---

 Checklist of optimisations:
- [ ]  STOPTREF ([task](https://github.com/tonlabs/TON-Solidity-Compiler/issues/135#issuecomment-1578306204))

**Comment by pyAndr3w** [comment]
1. may be replaced -> STOPTREF
![изображение](https://github.com/tonlabs/TON-Solidity-Compiler/assets/43111428/74edabb9-4f0d-4a9e-8823-47766081baea)

<hr>

solidity code for testing:
```solidity
function testFunc(optional(TvmCell) optCell) private {
    TvmBuilder b;
    b.store(optCell);
    tvm.setData(b.toCell());
}
```
current assembly:
```
.macro testFunc_7be240aa_internal_macro
NEWC
XCPU S1, S0
ISNULL
PUSHCONT {
	DROP
	STSLICECONST 0
}
PUSHCONT {
	SWAP
	STSLICECONST 1
	STREF
}
IFELSE
ENDC
POPROOT
```

expected assembly:
```
.macro testFunc_7be240aa_internal_macro
NEWC
STOPTREF
ENDC
POPROOT
```

|               |         |
| ------------------ | -------------- |
| potentially saves | 108-126 gas |
| compiler version | 0.69.0           |

**Comment by IgorKoval** [comment]
Thank you! We are going to implement it in v0.71.0
