### ISSUE TITLE
Proposal: Add the ability to attach stateinit when calling contract interface

### ISSUE THREAD

**Issue by pyAndr3w** [everx-labs/TVM-Solidity-Compiler#136]
Adding stateinit when calling the contract interface will allow you to "deploy" contracts without using a constructor. This will make it possible to create more flexible systems using more blockchain features (in TVM-based blockchains there is no concept of "deploy" as such)

expected syntax:
```solidity
IContract(address).testFunction{ value: 1 ever, stateInit: cell }();
```
or 
```solidity
IContract(address).testFunction{ value: 1 ever, stateInit: builder }();
```
or 
```solidity
IContract(address).testFunction{ value: 1 ever, stateInit: slice }();
```

**Comment by pyAndr3w** [comment]
ability to specify stateinit with different data types will allow to optimize the code for building a message cell

**Comment by BorisI** [comment]
Sounds reasonable. Thank you!

**Comment by IgorKoval** [comment]
Thank you! Added to 0.75 release
https://github.com/everx-labs/TVM-Solidity-Compiler/blob/master/API.md#external-function-calls
