### ISSUE TITLE
Proposal: Add variables to msg namespace

### ISSUE THREAD

**Issue by pyAndr3w** [everx-labs/TVM-Solidity-Compiler#138]
Adding these two variables will allow:
1. Find out how many coins were spent on forward (gas management)
2. Implement custom logic with message cell. (flexibility)

---

**msg.forwardFee**
```solidity
msg.forwardFee (varUint16)
```
Returns:
-  forward fee of the message for internal message.
-  import fee of the message for external message.

---

**msg.cell**
```solidity
msg.cell (TvmCell)
```
Returns:
-  Message X cell

**Comment by mnill** [comment]
this will be really useful for gas/value calculation in dapps. please prioritise this issue.

**Comment by cryshado** [comment]
@pyAndr3w This is definitely a valuable suggestion, thank you! I think we should implement separate `msg.forwardFee` and `msg.importFee` or/and provide access to `Message X` cell to allow parse these values independently. If `msg.forwardFee` returns the import fee in external messages, it would be unexpected behavior.

**Comment by cryshado** [comment]
Implemented in 0.71.0 (2023-07-20) #141
