### ISSUE TITLE
Proposal: change tx.timestamp naming

### ISSUE THREAD

**Issue by pyAndr3w** [everx-labs/TVM-Solidity-Compiler#139]
At the moment the variable which is logical time is named timestamp (`tx.timestamp`)

Although another variable, which is also a logical time, is named logicaltime (`block.logicaltime`)

---

I propose to change the current naming:

```solidity
tx.timestamp returns (uint64);
```

to correct naming:

```solidity
tx.logicaltime returns (uint64);
```

*(or create an alias)*

**Comment by IgorKoval** [comment]
Thank you! We fixed it https://github.com/tonlabs/TON-Solidity-Compiler/pull/140
