### ISSUE TITLE
block.logicaltime doesn't work & block.timestamp output's wrong unix time, ex:- "35012461000000" 

### ISSUE THREAD

**Issue by shravanandoria** [everx-labs/TVM-Solidity-Compiler#145]
![image](https://github.com/tonlabs/TON-Solidity-Compiler/assets/36509067/df631783-075e-4907-8843-029531515eb7)

Now when I read this in the frontend, I get this "35012461000000", I think it's not a valid unix time

**Comment by shravanandoria** [comment]
@IgorKoval Please take a look at it

**Comment by mnill** [comment]
Compiler version?

**Comment by shravanandoria** [comment]
> Compiler version?

0.61.2
@mnill

**Comment by mnill** [comment]
Logical time is Everscale related param. To get timestamp you need to use compiler with version >= 0.67.0 or try to use `now` instead of `block.timestamp `

https://github.com/tonlabs/TON-Solidity-Compiler/blob/master/Changelog.md

```
0.67.0 (2023-03-16)

Update compiler frontend (from original version 0.6.3 to 0.8.17):

Breaking changes:
block.timestamp returns opcode NOW instead of opcode BLOCKLT. block.logicaltime returns opcode BLOCKLT.
```
