### ISSUE TITLE
Compiler segfaults on internal function calls attributed with "{value: ...}" 

### ISSUE THREAD

**Issue by BorisI** [everx-labs/TVM-Solidity-Compiler#151]
pragma ton-solidity >= 0.73.0;
function bar() {}
contract call {
    function foo() internal {
        bar{value: 1}();
    }
}

$ sold call.sol
Segmentation fault
$ sold --version
sold 0.73.0+commit.82d8855a.mod.Linux.g++

**Comment by IgorKoval** [comment]
Thank you! It will be fixed in v0.74.0.
