### ISSUE TITLE
Compiler generates invalid code for library function calls by reference

### ISSUE THREAD

**Issue by BorisI** [everx-labs/TVM-Solidity-Compiler#153]
for source code:

pragma ton-solidity >= 0.74.0;

contract tce {
    function fail() external pure {
        bar sc;
        sc.mbaz[1] = 0;
        sc.foo();
    }
}
struct bar {
    mapping (uint16 => uint8) mbaz;
}
using libbar for bar global;
library libbar {
    function foo(bar s) internal {
        for ((, uint8 v): s.mbaz) {
            v;
            uint8 val;
            if (val == 1)
                return;
        }
    }
}

$ ever-cli -c etc/tce.conf debug run -m fail

generates trace: 
...
107 3753 18 ISNULL tce.sol:16
108 3771 18 NOT tce.sol:16
109 3776 5 implicit RET 
109 3776 0 RET FROM WHILE tce.sol:16
110 3794 18 IFRET build/tce.code:98
111 3844 0 UNHANDLED EXCEPTION: VM Exception: type check error, code 7, value: 0 ...src/stack/mod.rs:447 CMD: IFRET err: item is not an integer build/tce.code:98

**Comment by IgorKoval** [comment]
Thank you! It will be fixed in v0.75.0.
