### ISSUE TITLE
tvm.functionId() for getting constructor id

### ISSUE THREAD

**Issue by rightjelkin** [everx-labs/TVM-Solidity-Compiler#24]
According to TON Solidity API, I can make something like this for getting public constructor id:
`tvm.functionId(Contract)`
But compiler return an error `This function takes one argument (identifier of public function)`.
How can I get public constructor id?

('latest' tag of image  tonlabs/compilers is used for compilation)

**Comment by SilkovAlexander** [comment]
Thank you for your report. We will try to update that container. Now you can build the compiler and use this function as you described

**Comment by BorisI** [comment]
Is there a problem with the compiler built from the sources of this repository? If there is, it should be addressed here. If there is a container of some sort with an outdated contents, the problem should be addressed somewhere else.

**Comment by rightjelkin** [comment]
Yep. I built compiler from this repository and now code successfully compiled. I think issue can be closed, but as for me usage of container is more handy, and it will be nice if you update docker image. Thanks.
