### ISSUE TITLE
Add constants for flags and error codes

### ISSUE THREAD

**Issue by NoamDev** [everx-labs/TVM-Solidity-Compiler#49]
Usual solidity contracts are full of numeric flags like 64.
It's inconvenient to look those up each time, but you'd want yo make sure you are not mistaken.
I suggest to add compile time constants with meaningful names.

So for example instead of:

``` solidity
msg.sender.transfer({value:0, flag:64, bounce:false})
```

You would have:

``` solidity
msg.sender.transfer({value:0, flag:flags.REMAINING_GAS, bounce:false})
```

**Comment by cryshado** [comment]
@NoamDev Thanks for the issue! You can easily do this yourself using the constants.
