### ISSUE TITLE
Segmentation fault when using format function

### ISSUE THREAD

**Issue by Pafaul** [everx-labs/TVM-Solidity-Compiler#52]
If you use ```format``` function to insert values, if you provide empty string, it results in ```Segmentation fault``` error.
If you provide non-empty string without placeholders than you get message that number of placeholders is invalid:
```
Error: Number of arguments is not equal to the number of placeholders!
 --> TEST.sol:8:9:
  |
8 |         format("asdfadfa", 1, 2, 3);
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
  But empty string results in ```Segmentation fault```.
  
  Test contract:
```solidity
pragma ton-solidity >= 0.39.0;
pragma AbiHeader expire;
pragma AbiHeader pubkey;
pragma AbiHeader time;

contract TEST {
    function someFunction() {
        format("", 1, 2, 3);
    }
}
```

Tested with v0.39.0 compiler and v0.43.0 compiler.

**Comment by IgorKoval** [comment]
Thank you, fixed
