### ISSUE TITLE
tvm.rawReserve() issue

### ISSUE THREAD

**Issue by Pafaul** [everx-labs/TVM-Solidity-Compiler#70]
Issue: if you use ```tvm.rawReserve()``` to split the ton flow (for example - for two calls check example below), strange behavior apper.

Case:
We have a contract, that wants to call two other contracts during one call (otherwise there will be too much additional code):
```solidity
interface ContractToCall1 {
    function toCall(TvmCell args) external;
}

interface ContractToCall2 {
    function toCall2(TvmCell args) external;
}

contract TestContract {
    function splitTonFlow(TvmCell args1 , TvmCell args2) {
         tvm.rawReserve(msg.value / 2, 0);

         ContractToCall2(knownAddress2).toCall{
         value: msg.value / 2
        }(args1);

        ContractToCall1(knownAddress1).toCall{
             flag: 64
        }(args1);
    }
}
```  

Expected behavior:
Produce two messages with attached value:
1. For ContractToCall2 - msg.value / 2
2. For ContractToCall1 - (msg.value / 2 - fees)

Contract behavior:
Producing two messages with values:
1. For ContractToCall2 - msg.value / 2
2. For ContractToCall1 - (msg.value - fees)

So there is a problem with splitting TON flow. This is a problem if you try to implement complex systems, which are not always pretty with only linear call scheme.

Cannot provide real source code here, for more info - please contact me (tg: @pafaul)

**Comment by Pafaul** [comment]
Forgot to mention: 
used compiler - v0.47.0, stdlib - 0.47.0, linker - latest at the moment of writing this comment

**Comment by IgorKoval** [comment]
Hello,
use such code to split the funds
```
    function g() public view {
        // reverse original balance (before receiving msg.value)
        tvm.rawReserve(0, 4);
        // send half
        address(123).transfer({value: msg.value / 2, flag: 0, bounce: false});
        // send rest funds
        address(321).transfer({value: 0, flag: 128, bounce: false});
    }
```

**Comment by Pafaul** [comment]
Problem is closed, probably some docs enhancement is required :)
