### ISSUE TITLE
install_deps.sh on mac os upgrade all packages installed via brew

### ISSUE THREAD

**Issue by mnill** [everx-labs/TVM-Solidity-Compiler#74]
It is like
`apt-get upgrade`
is it necessary?

https://github.com/tonlabs/TON-Solidity-Compiler/blob/df41049ebed5f8b0695dea161a529393c2368090/compiler/scripts/install_deps.sh#L115

**Comment by IgorKoval** [comment]
thank you, done. See v0.53.0
