### ISSUE TITLE
Proposal: encodeFunctionParam

### ISSUE THREAD

**Issue by mnill** [everx-labs/TVM-Solidity-Compiler#78]
Will be good to have encodeFunctionParam function by analogy with decodeFunctionParams,

Simple use case - contract upgrade:

```
function stateParams(
    uint32 _version,
    address _root,
    mapping (address => uint128) _balances,
    mapping (address => uint128) _approvedAddresses,
) public {}

function codeUpgrade(TvmCell _code) override external onlyRoot {
    TvmCell data = tvm.encodeFunctionParam(stateParams, version,  root, balances, approvedAddresses);

    tvm.setcode(_code);
    tvm.setCurrentCode(_code);

    onCodeUpgrade(data);
}

function onCodeUpgrade(TvmCell _data) private {
    tvm.resetStorage();
    TvmSlice state = _data.toSlice();
    (stateParams, version,  root, balances, approvedAddresses) = state.decodeFunctionParams(stateParams);
}
```

Also there can be more complicated use cases, like encode params for call in contract A, send it to contract B to approve by multisig/dao, and then call contract C with this TvmCell.

**Comment by mnill** [comment]
I found tvm.encodeBody() but it does not make the trick, looks like it also contain functionID or some another additional data.

**Comment by IgorKoval** [comment]
Thank you for your idea. It will be useful! We are going to support this.

**Comment by IgorKoval** [comment]
Added this feature in v0.55
