### ISSUE TITLE
Rename ton-solidity in tvm-solidity

### ISSUE THREAD

**Issue by ilyar** [everx-labs/TVM-Solidity-Compiler#94]
Will consistently rename `pragma ton-solidity` in `pragma tvm-solidity` and repo too

**Comment by pizza-777** [comment]
Tvm is abbreviation of Ton Virtual Machine. So it's the same "TON". What is the difference?

Maybe better "evm-solidity" ? EVM is meant as Everscale Virtual Machine.

**Comment by ilyar** [comment]
It is important to keep in mind that it is important to find an elegant solution in which our terms will not create conflicts with the already established ones:
**EVM** — logical but already busy — Ethereum Virtual Machine
**EIP** — is the same — Electoral Integrity Project

The current position for **TIP** is Trustless Improvement Proposal for TVM, it seems there is no position yet, but I think there are a lot of words for the letter T.

**TVM** — TON Virtual Machine, in reality, the VM in Everscale is a VM based on TON Virtual Machine and over time, it is possible that it may become incompatible already now it has operations that are missing in the based architecture, sso it will be sequential:
**TVM** — Trustless Virtual Machine (based on TON Virtual Machine)

At the same time, this approach does not take into account the future development of history, the current manipulations with the explanation of abbreviations suggest the unconditional popularity of terms, while in the current reality there are already two projects in which these terms (TIP and TVM) mean different things.

Therefore, it would probably make more sense to replace the letter T with the abbreviation of the project name for Everscale as ES (similar to Microsoft shortening to MS), therefore the terms will be **ESIP** and **ESVM**.

For certainty, more opinions are needed from active participants contributing to the project.

**Comment by pizza-777** [comment]
ever-solidity

**Comment by ilyar** [comment]
https://github.com/EverscaleGuild/ever-solidity
