### ISSUE TITLE
contract constructor can't be external

### ISSUE THREAD

**Issue by cryshado** [everx-labs/TVM-Solidity-Compiler#98]
When I try to compile the following code:
```solidity
pragma ton-solidity >=0.59.4;

contract Test {
    constructor() external internalMsg { }
}   
```

I get an error: `Error: Constructor must be public or internal.` I want to allow deploy my smart contract by internal message without making the constructor call available inside the contract, but I can't do that. I think this seems to be an issue.

**Comment by webala** [comment]
The constructor cannot be explicitly "called" from within the contract hence no need for external modifier. Furthermore, external keyword on constructors causes issues with inheritance.
